### ISSUE TITLE
Modal text/String Input

### ISSUE THREAD

**Issue by sorenhan** [microsoft/mixed-reality-extension-sdk#135]
The functionality would probably come in as a component of any grand unifying UI system, but maybe we could deliver a standalone solution sooner? 

Maybe a host-app independent interface for "enter a text string", where the host app can decide to show a virtual keyboard (with text entry field), or pop up a messagebox itself.

**Comment by willneedit** [comment]
`User.showKeyboard(defaultInput?: string): Promise<string>;`

comes to my mind. This function could pop up the virtual keyboard, optionally pre-filled with some content, and the resolved promise would hold the actual user input, or the unchanged default.

Rejected promises could come with an error code denoting the reason, where 'cancelled' might be the most obvious one, but still leaves room for cases where it's not feasible to show a keyboard (because it is already shown because of another text input, a dialog is open, ...)

**Comment by eanders-MS** [comment]
Hi @willneedit I was thinking along similar lines, though wanted to include a prompt title as well:
```ts
User.textPrompt(options?: {
    title?: string, // dialog prompt
    value?: string // prefilled value
}): Promise<string>;
```
I'd like to not have to wrap every call to textPrompt in a try/catch to handle user-cancellation which really is a non-error. Probably better to return null if user cancels:
```ts
const username = await user.textPrompt({ title: "What's your name?" });
if (username) {
    console.log(`Hello ${username}`);
} else {
    console.log("user cancelled");
}
```

**Comment by willneedit** [comment]
null, as opposed to an empty string, which someone could voluntarily enter. Good catch, and makes things lot easier.
