### ISSUE TITLE
[RFC] Animation system design goals

### ISSUE THREAD

**Issue by stevenvergenz** [microsoft/mixed-reality-extension-sdk#460]
The current animation system is very minimal, so the time has come to rebuild it stronger and more useful. Before the design process can really get rolling, we need to clarify our objectives, the needs that this system should satisfy. I've listed the ones I've come up with, based on a survey of what features other animation libraries and game engines have. Please review, and comment if you think any need to be modified or added.

1. Native animations - Animations added to actors from glTF or native Unity sources should support the basic API: play, pause, seek.
2. Keyframes - Vary actor/asset fields through a sequence of values on a timeline.
	1. Interpolation - Make simple single-target two-frame animations easy to generate.
	2. Moving targets - Setting/interpolating to/from another actor's dynamic values. Useful for look-at and fly-to type animations.
3. Easing - Support different interpolation curves between keyframes.
    1. No easing - Setting fields that cannot be interpolated should also be supported (string, boolean, etc.).
4. Chaining - Begin an animation immediately after another finishes, or on some other event (behavior tie-in?)
5. Multiple targets - Animate multiple actors/assets, and multiple properties, in lock-step (equivalent to Unity's animation curves)

**Comment by eanders-MS** [comment]
I love that we're starting here. This is such an important subsystem to get right.

**Comment by eanders-MS** [comment]
I see the value of Chaining, but might be a difficult one to get right without adding a lot of complexity to the API. I would prioritize it downward, possibly not explicitly support it all. Awaiting on a completion promise should suffice in most cases.

**Comment by stevenvergenz** [comment]
I think the main thing I would use chaining for is for animations as a substitute for simulated rigidbody physics. Hard to imagine a Newton's Cradle with a 50ms delay between impact and motion transfer. Maybe it's enough to say that any proposal should allow chaining, though I'd like to at least explore this for animations.

**Comment by adbalano** [comment]
Some random thoughts for consideration:

-For item 4 - I would want to be able to blend between different animations/poses. Useful for transitions. 
-I would potentially want to define blend ranges between two animations.
-I want to define entry and exit ranges in animations. Although maybe this is handled by some state machine logic? For example, given an event that occurs during the playback of one animation, play a different animation at a different time range than you would otherwise.
-For any animation, I want to be able to define anim events based on time/frames of animation.
- I want to be able to manipulate playback rate (0.5x, 2x, etc)
-Support anim events added to an animation from 3d package.
-It would be useful to be able to reuse animations. Example - I have a rigged character with a 8-way turn, walk, run, sprint animation set. I have 5 different characters that use the same rig. I want to use my one set of locomotion animations for the 5 different characters.
-Not sure if needed to do within the MRE but something to consider might be the ability to retarget animations.
