### ISSUE TITLE
version issue in package.json 

### ISSUE THREAD

**Issue by djzielin** [microsoft/mixed-reality-extension-sdk#535]
https://github.com/microsoft/mixed-reality-extension-sdk/blob/red/packages/sdk/package.json

the mixed-reality-extension-common is requiring 0.16 but only 0.1.0 exists

**Comment by eanders-MS** [comment]
That package hasn't been published yet. The link above is referencing the red branch. This branch is where we do development. When we make a release, we merge red to master, then publish from master. The common package will be released in 0.17.

If I knew more about why you're referencing the red branch, I might be able to help further.

**Comment by djzielin** [comment]
When you go the website, it's defaulted to the red branch. When you clone, you start out on the red branch. Not sure why. Perhaps the default branch setting in github for the repository is set to red?

**Comment by eanders-MS** [comment]
That's correct, our default branch is set to red. This is because all PRs should target red. Anyone interested in making a change to the SDK should target the red branch. Having red as the default makes it less likely someone will develop and open a PR against master.

There are a few reasons you might want to work from SDK source rather than use the npm package:
1/ You are interested in making changes to the SDK. 
2/ You want access to a feature that isn't released yet.

For these scenarios, it makes sense to clone the repo and have your project reference the local copy. The `npm link` command is convenient for setting up this local dependency. Is this what you're doing?

**Comment by stevenvergenz** [comment]
The common package has been updated.
