### ISSUE TITLE
Physics prediction

### ISSUE THREAD

**Issue by nik0la31** [microsoft/mixed-reality-extension-sdk#616]
- [x] predict remote rigid body simulation when in collision with local rigid body
- [ ] predict remote rigid bodies when there is missing updates from jitter buffer

**Comment by jabenk** [comment]
As discussed in the meeting the second feature "predict remote rigid bodies when there is missing updates from jitter buffer" was implemented in a user branch but it turns out that this is not necessary for the first version, since the user experience is good even without this feature with the new version of the jitter buffer.
And for long time network outages (100ms - 2s) the current behavior to just "freeze" the bodies, is also accepted (instead of turning them dynamic with the last received extracted velocity).

As a conclusion to keep to code simpler we will not PR this feature into the main branch and will wait for the first feedback of the current version to see where improvements are necessary.

**Comment by jabenk** [comment]
The first feature "predict remote rigid body simulation when in collision with local rigid bodies" was already implemented and is part of the current version. 
Additional improvements to it, if needed, will be done in the frame of a different issue.
